import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import Homepage from "./components/homepage";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Astral Paints",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Homepage/>
        <Footer />
      </body>
    </html>
  );
}
